Urb 31 post reserve
utaipei-sa/api.reserve.utsa pull request #54
Opened 2024-06-24 09:33 UTC by nickchengtw

- 將 POST /reservation 的程式搬到 POST /reserve
- 更改回傳格式
- 更新 OpenAPI 文件

2024-06-28 06:44 UTC, Jeff92316046 commented
reviewer應該多加一個給 @Chun-Cheng

2024-06-28 07:40 UTC, Chun-Cheng requested changes
- Linter 有給一些錯誤
- 有一些垃圾可以清掉？
- 舊的 post_reservation.js 要刪掉嗎？

2024-06-28 07:55 UTC, Chun-Cheng commented
https://linear.app/utaipei-sa/issue/URB-31/post-reserve-新增預約資料#comment-6b21f773
這些測資都有通過嗎？

2024-06-28 11:48 UTC, nickchengtw commented
我原本想說之後寫測試程式
我現在先手動測

2024-06-28 12:15 UTC, nickchengtw commented
> * Linter 有給一些錯誤
> * 有一些垃圾可以清掉？
> * 舊的 post_reservation.js 要刪掉嗎？

垃圾是指被註解掉的程式嗎?

2024-06-29 09:14 UTC, nickchengtw commented
我手動測試完了

2024-06-29 09:42 UTC, Chun-Cheng commented
> > * Linter 有給一些錯誤
> > * 有一些垃圾可以清掉？
> > * 舊的 post_reservation.js 要刪掉嗎？
> 
> 垃圾是指被註解掉的程式嗎?

是

2024-07-05 04:00 UTC, Chun-Cheng approved these changes
Test passed.

2024-07-05 05:02 UTC, merged

2024-07-17 15:30 UTC, Chun-Cheng commented
抱歉回馬槍
這裡的時間似乎沒有處理到時區的問題，錯把+8的時間直接當作 UTC 的時間存入資料庫（例如：應為 `2024-07-17T23:00:00.000+0800` 存成 `2024-07-17T23:00:00.000Z`），可能要再處理一下

2024-07-18 02:48 UTC, nickchengtw commented
> 抱歉回馬槍 這裡的時間似乎沒有處理到時區的問題，錯把+8的時間直接當作 UTC 的時間存入資料庫（例如：應為 `2024-07-17T23:00:00.000+0800` 存成 `2024-07-17T23:00:00.000Z`），可能要再處理一下

這個PR已經merge了
把這個問題開在新的issue好了