Barney9211/urb 18 delete reservereservation id 刪除預約資料
utaipei-sa/api.reserve.utsa pull request #57
Opened 2024-07-03 03:46 UTC by Barney9211

修復item如果同時有兩個人都預約了會一起刪除的bug
ex:今天item有30張椅子，A借了13張 B借了5張，在刪除B的時候會連A一起刪掉

2024-07-03 07:10 UTC, nickchengtw commented on routes/reserve/delete_reservation.js
> +    console.log("AAAA")
這個AAAA應該可以不用?

2024-07-03 07:28 UTC, nickchengtw commented on routes/reserve/delete_reservation.js
> +    let tempID;
tempQuantity沒有在迴圈外面用到
可以移到迴圈裏面?
這兩個變數的名稱前面因該不用加temp

2024-07-03 08:14 UTC, Barney9211 commented on routes/reserve/delete_reservation.js
> +    let tempID;
OK!!!!

2024-07-03 08:19 UTC, nickchengtw commented on routes/reserve/delete_reservation.js
> +        _id: ID//filter
如果ID只用到一次的話因該就不用再宣告成變數了

2024-07-03 08:21 UTC, nickchengtw commented on routes/reserve/delete_reservation.js
> +        _id: tempID//filter
同上

2024-07-03 08:24 UTC, nickchengtw commented
Linear上面的路徑有改過
OpenAPI跟router的路徑要改成Linear上面的樣子

2024-07-03 12:25 UTC, nickchengtw commented
被註解的程式因該可以先刪掉?

2024-07-03 12:30 UTC, nickchengtw commented
順便把Linter的錯誤都修掉

2024-07-05 03:24 UTC, nickchengtw commented
在swagger上沒辦法用
不知道是 openapi 文件還是程式的問題
![Screenshot 2024-07-05 112105](https://github.com/utaipei-sa/api.reserve.utsa/assets/33611456/6056c347-c2ae-4c6f-8fcc-0171739b5b28)

2024-07-05 03:42 UTC, nickchengtw commented on routes/reserve/delete_reservation.js
> +      reservation_quantity = reservation_find.item_reservations[0].quantity
看起來它這邊取消預約的時候只取第一個預約的物品的量?
如果這筆預約預約了多個物品
其他物品被取消的量會不會變成其實是取消了第一個物品的量?

2024-07-05 04:09 UTC, Chun-Cheng commented
> 在swagger上沒辦法用 不知道是 openapi 文件還是程式的問題 ![Screenshot 2024-07-05 112105](https://private-user-images.githubusercontent.com/33611456/345991409-6056c347-c2ae-4c6f-8fcc-0171739b5b28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTI0MDcsIm5iZiI6MTcyMDE1MjEwNywicGF0aCI6Ii8zMzYxMTQ1Ni8zNDU5OTE0MDktNjA1NmMzNDctYzJhZS00YzZmLThmY2MtMDE3MTczOWI1YjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA0MDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmFhOWZkMTVmZmZhYzY4M2I5Yzc5M2Q2OWY3OTJjZThiZGEwNDI4YmY4OTA5YTE1ZGU5MmVmMDVkYTkxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fPM0wvMRmKzRenZGmXt-fRGv6JdDyA2IopNGNfbE4Xo)

答案是都有錯😄

2024-07-05 04:10 UTC, Chun-Cheng requested changes

2024-07-05 04:10 UTC, Chun-Cheng commented on routes/reserve/delete_reservation.js
> + * /reserve/{reservation_id}:
改成 `/reserve/reserve/{reservation_id}`

2024-07-05 04:10 UTC, Chun-Cheng commented on routes/reserve/delete_reservation.js
> +router.delete('/reserve/{reservation_id}', async function (req, res, next) {
路徑改成 `'/reserve/:reservation_id'`
（不用`{}`，用`:`）

2024-07-05 04:16 UTC, Chun-Cheng commented
建議 delete_reservation.js 的檔名改成 delete_reserve.js

2024-07-05 05:19 UTC, Barney9211 commented on routes/reserve/delete_reservation.js
> +      reservation_quantity = reservation_find.item_reservations[0].quantity
看起來好像確實是這樣😢
但我可能要星期日才能改 不好意思😢

2024-07-05 05:21 UTC, Barney9211 commented on routes/reserve/delete_reservation.js
> +router.delete('/reserve/{reservation_id}', async function (req, res, next) {
好ㄉ！

2024-07-08 13:31 UTC, nickchengtw commented
預約取消後mongodb裡的spaces_reserved_time裡面的資料還會留著
只是document的reserved會變成 0
是不是要把整筆document刪掉?
![Screenshot 2024-07-08 212801](https://github.com/utaipei-sa/api.reserve.utsa/assets/33611456/e98cf006-f184-41cf-a376-0ada525927b6)

2024-07-12 04:28 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      .json({ error: 'reservation_id is required' })
這個 error 應該要改成 linear 上面的格式

2024-07-12 04:28 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      .json({ error: 'reservation_id format error' })
同上

2024-07-12 04:30 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +    })
應該不用回傳陣列?
linear 上面是直接回傳
```
{
      code: R_ID_NOT_FOUND,
      message: 'Reservation ID not found'
}
```

2024-07-12 04:31 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      })
同上

2024-07-13 15:36 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      })
error可以改用response.js裡的error_response統一錯誤格式

2024-07-13 15:36 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      })
同上

2024-07-13 15:36 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      })
同上

2024-07-16 06:06 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      .json(error_response(R_SUCCESS, 'Delete success!'))
這邊因該不用用error_response
因為它不是錯誤

2024-07-16 06:09 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
error_response忘了import了
```
file:///D:/api.reserve.utsa/routes/reserve/delete_reserve.js:59
      .json(error_response(R_ID_NOT_FOUND, 'Reservation ID not found'))
      ^

ReferenceError: error_response is not defined
    at file:///D:/api.reserve.utsa/routes/reserve/delete_reserve.js:59:7
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.1
[nodemon] app crashed - waiting for file changes before starting...
```

2024-07-16 06:57 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      }
這裡為什麼要先把reservation_find.item_reservations存到storeReserveInfo陣列
然後再從storeReserveInfo裡找到各個item要被刪除的quantity?
能不能直接從reservation_find.item_reservations找到各個item要被刪除的quantity

2024-07-17 03:17 UTC, Barney9211 commented on routes/reserve/delete_reserve.js
> +      }
因為我當初直接叫reservation_find.item_reservations裡面的東西的時候有點問題，所以就用了看起來有點多此一舉的方法，但我忘記是啥問題了w

2024-07-17 04:16 UTC, nickchengtw commented on routes/reserve/delete_reserve.js
> +      }
那就先不改

2024-07-17 04:32 UTC, nickchengtw approved these changes, later dismissed

2024-07-17 04:49 UTC, Chun-Cheng commented on routes/reserve/delete_reserve.js
> + *     responses:
文件可以把錯誤代碼加上去

2024-07-19 12:18 UTC, Chun-Cheng commented
狀態碼 200 OK 的回傳內容，用 error_code 不太適合，可以參考一下這個：https://github.com/utaipei-sa/api.reserve.utsa/blob/main/routes/reserve/post_reserve.js

2024-07-19 12:44 UTC, Chun-Cheng submitted a review, later dismissed
👍

2024-07-22 05:32 UTC, Jeff92316046 approved these changes

2024-07-22 05:33 UTC, merged